apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: frontend
  namespace: hotel-res
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: frontend
  strategy: {}
  template:
    metadata:
      name: frontend
      labels:
        death-star-project: hotel-res
        app-name: frontend
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - command:
        - frontend
        env:
        - name: DLOG
          value: DEBUG
        image: image-registry.openshift-image-registry.svc:5000/hotel-res/hotel_reserv_frontend_single_node
        name: hotel-reserv-frontend
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /go/src/github.com/harlow/go-micro-services/config.json
          subPath: config.json
          name: config-json
      restartPolicy: Always
      volumes:
      - name: config-json
        configMap:
          name: configmap-config-json
          items:
          - key: config.json
            path: config.json
status: {}
