apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    death-star-project: hotel-res
    app-name: memcached-rate
  namespace: hotel-res
  name: memcached-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: hotel-res
      app-name: memcached-rate
  strategy: {}
  template:
    metadata:
      name: memcached-rate
      labels:
        death-star-project: hotel-res
        app-name: memcached-rate
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: MEMCACHED_CACHE_SIZE
          value: "128"
        - name: MEMCACHED_THREADS
          value: "2"
        image: memcached
        name: hotel-reserv-rate-mmc
        command: ["memcached", "-c", "65536"]
        ports:
        - containerPort: 11211
        resources: {}
      restartPolicy: Always
status: {}
