name: user-memcached

ports:
  - port: 11211
    targetPort: 11211

container:
  image: library/memcached
  imageVersion: 1.6.7
  name: user-memcached
  ports: 
  - containerPort: 11211

configMaps:
  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config
