name: rate

ports:
  - port: 8084
    targetPort: 8084
 
container:
  command: rate
  image: deathstarbench/hotel-reservation
  name: hotel-reserv-rate
  ports:
  - containerPort: 8084
  environments:
    logLevel: INFO
    jaegerSampleRatio: 1

configMaps:
  - name: service-config.json
    mountPath: /go/src/github.com/harlow/go-micro-services/config.json
    value: service-config
