name: compose-review-memcached

ports:
  - port: 11211
    targetPort: 11211

container:
  image: library/memcached
  imageVersion: 1.6.7
  name: compose-review-memcached
  ports:
    - containerPort: 11211

configMaps:
  - name: jaeger-config.yml
    mountPath: /media-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /media-microservices/config/service-config.json
    value: service-config
