name: post-storage-mongodb

ports:
  - port: 27017
    targetPort: 27017

container:
  args: 
  - --config
  - /social-network-microservices/config/mongod.conf
  image: library/mongo
  imageVersion: 4.4.6
  name: post-storage-mongodb
  ports: 
  - containerPort: 27017

configMaps:
  - name: mongod.conf
    mountPath: /social-network-microservices/config/mongod.conf
    value: mongod
