version: "2"
services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always

  frontend:
    build: .
    image: hotel_reserv_frontend_single_node
    entrypoint: frontend
    container_name: 'hotel_reserv_frontend'
    ports:
      - "5000:5000"
    depends_on:
      - consul
    restart: always
    cpuset: "0"

  profile:
    build: .
    image: hotel_reserv_profile_single_node
    entrypoint: profile
    container_name: 'hotel_reserv_profile'
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-profile
      - memcached-profile
      - consul
    restart: always
    cpuset: "0"

  search:
    build: .
    image: hotel_reserv_search_single_node
    entrypoint: search
    container_name: 'hotel_reserv_search'
    ports:
      - "8082:8082"
    depends_on:
      - consul
    restart: always
    cpuset: "0"
    # environment:
      # - GRPC_GO_LOG_VERBOSITY_LEVEL=2
      # - GRPC_GO_LOG_SEVERITY_LEVEL=info

  geo:
    build: .
    image: hotel_reserv_geo_single_node
    entrypoint: geo
    container_name: 'hotel_reserv_geo'
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-geo
      - consul
    restart: always
    cpuset: "0"

  rate:
    build: .
    image: hotel_reserv_rate_single_node
    entrypoint: rate
    container_name: 'hotel_reserv_rate'
    ports:
      - "8084:8084"
    depends_on:
      - mongodb-rate
      - memcached-rate
      - consul
    restart: always
    cpuset: "0"

  recommendation:
    build: .
    image: hotel_reserv_recommend_single_node
    entrypoint: recommendation
    container_name: 'hotel_reserv_recommendation'
    ports:
      - "8085:8085"
    depends_on:
      - mongodb-recommendation
      - consul
    restart: always
    cpuset: "0"

  user:
    build: .
    image: hotel_reserv_user_single_node
    entrypoint: user
    container_name: 'hotel_reserv_user'
    ports:
      - "8086:8086"
    depends_on:
      - mongodb-user
      - consul
    restart: always
    cpuset: "0"

  reservation:
    build: .
    image: hotel_reserv_rsv_single_node
    entrypoint: reservation
    container_name: 'hotel_reserv_reservation'
    ports:
      - "8087:8087"
    depends_on:
      - mongodb-reservation
      - memcached-reserve
      - consul
    restart: always
    cpuset: "0"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: 'hotel_reserv_jaeger'
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always
    cpuset: "0"

  memcached-rate:
    image: memcached
    # hostname: user-memcached
    container_name: 'hotel_reserv_rate_mmc'
    ports:
     - 11212:11211
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    cpuset: "0"

  memcached-profile:
    image: memcached
    # hostname: user-memcached
    container_name: 'hotel_reserv_profile_mmc'
    ports:
     - 11213:11211
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    cpuset: "0"

  memcached-reserve:
    image: memcached
    # hostname: user-memcached
    container_name: 'hotel_reserv_reservation_mmc'
    ports:
     - 11214:11211
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    cpuset: "0"

  mongodb-geo:
    image: mongo
    container_name: 'hotel_reserv_geo_mongo'
    # hostname: geo-db
    ports:
      - "27018:27017"
    restart: always
    cpuset: "0"
    volumes:
      - geo:/data/db  

  mongodb-profile:
    image: mongo
    container_name: 'hotel_reserv_profile_mongo'
    hostname: profile-db
    ports:
      - "27019:27017"
    restart: always
    cpuset: "0"
    volumes:
      - profile:/data/db    

  mongodb-rate:
    image: mongo
    container_name: 'hotel_reserv_rate_mongo'
    hostname: rate-db
    ports:
      - "27020:27017"
    restart: always
    cpuset: "0"
    volumes:
      - rate:/data/db   

  mongodb-recommendation:
    image: mongo
    hostname: recommendation-db
    container_name: 'hotel_reserv_recommendation_mongo'
    ports:
      - "27021:27017"
    restart: always
    cpuset: "0"
    volumes:
      - recommendation:/data/db
    
  mongodb-reservation:
    image: mongo
    container_name: 'hotel_reserv_reservation_mongo'
    hostname: reservation-db
    ports:
      - "27022:27017"
    restart: always
    cpuset: "0"
    volumes:
      - reservation:/data/db 

  mongodb-user:
    image: mongo
    container_name: 'hotel_reserv_user_mongo'
    hostname: user-db
    ports:
      - "27023:27017"
    restart: always
    cpuset: "0"
    volumes:
      - user:/data/db
    
volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user: