version: "2"
services:
  consul:
    image: hashicorp/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always

  frontend:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    build: .
    image: hotel_reserv_frontend_single_node
    entrypoint: frontend
    container_name: 'hotel_reserv_frontend'
    ports:
      - "5000:5000"
    depends_on:
      - consul
    restart: always

  profile:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - MEMC_TIMEOUT
      - LOG_LEVEL
    build: .
    image: hotel_reserv_profile_single_node
    entrypoint: profile
    container_name: 'hotel_reserv_profile'
    depends_on:
      - mongodb-profile
      - memcached-profile
      - consul
    restart: always

  search:
    build: .
    image: hotel_reserv_search_single_node
    entrypoint: search
    container_name: 'hotel_reserv_search'
    depends_on:
      - consul
    restart: always
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
      # - GRPC_GO_LOG_VERBOSITY_LEVEL=2
      # - GRPC_GO_LOG_SEVERITY_LEVEL=info

  geo:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    build: .
    image: hotel_reserv_geo_single_node
    entrypoint: geo
    container_name: 'hotel_reserv_geo'
    depends_on:
      - mongodb-geo
      - consul
    restart: always

  rate:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - MEMC_TIMEOUT
      - LOG_LEVEL
    build: .
    image: hotel_reserv_rate_single_node
    entrypoint: rate
    container_name: 'hotel_reserv_rate'
    depends_on:
      - mongodb-rate
      - memcached-rate
      - consul
    restart: always

  recommendation:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    build: .
    image: hotel_reserv_recommend_single_node
    entrypoint: recommendation
    container_name: 'hotel_reserv_recommendation'
    depends_on:
      - mongodb-recommendation
      - consul
    restart: always

  user:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    build: .
    image: hotel_reserv_user_single_node
    entrypoint: user
    container_name: 'hotel_reserv_user'
    depends_on:
      - mongodb-user
      - consul
    restart: always

  reservation:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - MEMC_TIMEOUT
      - LOG_LEVEL
    build: .
    image: hotel_reserv_rsv_single_node
    entrypoint: reservation
    container_name: 'hotel_reserv_reservation'
    depends_on:
      - mongodb-reservation
      - memcached-reserve
      - consul
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: 'hotel_reserv_jaeger'
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always

  memcached-rate:
    image: memcached
    # hostname: user-memcached
    container_name: 'hotel_reserv_rate_mmc'
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m

  memcached-profile:
    image: memcached
    # hostname: user-memcached
    container_name: 'hotel_reserv_profile_mmc'
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m

  memcached-reserve:
    image: memcached
    # hostname: user-memcached
    container_name: 'hotel_reserv_reservation_mmc'
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m

  mongodb-geo:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_geo_mongo'
    # hostname: geo-db
    restart: always
    volumes:
      - geo:/data/db  

  mongodb-profile:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_profile_mongo'
    hostname: profile-db
    restart: always
    volumes:
      - profile:/data/db    

  mongodb-rate:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_rate_mongo'
    hostname: rate-db
    restart: always
    volumes:
      - rate:/data/db   

  mongodb-recommendation:
    image: mongo:4.4.6
    hostname: recommendation-db
    container_name: 'hotel_reserv_recommendation_mongo'
    restart: always
    volumes:
      - recommendation:/data/db
    
  mongodb-reservation:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_reservation_mongo'
    hostname: reservation-db
    restart: always
    volumes:
      - reservation:/data/db 

  mongodb-user:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_user_mongo'
    hostname: user-db
    restart: always
    volumes:
      - user:/data/db
    
volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user:
