version: "3"
services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  frontend:
    environment:
      - TLS
    image: igorrudyk1/hotel_reserv_frontend_single_node:latest
    entrypoint: frontend
    ports:
      - "5000:5000"
    depends_on:
      - consul
    deploy:
      replicas: 3
      restart_policy:
        condition: any

  profile:
    environment:
      - TLS
    image: igorrudyk1/hotel_reserv_profile_single_node:latest
    entrypoint: profile
    depends_on:
      - mongodb-profile
      - memcached-profile
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  search:
    image: igorrudyk1/hotel_reserv_search_single_node:latest
    entrypoint: search
    depends_on:
      - consul
    environment:
      - TLS
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  geo:
    environment:
      - TLS
    image: igorrudyk1/hotel_reserv_geo_single_node:latest
    entrypoint: geo
    depends_on:
      - mongodb-geo
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  rate:
    environment:
      - TLS
    image: igorrudyk1/hotel_reserv_rate_single_node:latest
    entrypoint: rate
    depends_on:
      - mongodb-rate
      - memcached-rate
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  recommendation:
    environment:
      - TLS
    image: igorrudyk1/hotel_reserv_recommendation_single_node:latest
    entrypoint: recommendation
    depends_on:
      - mongodb-recommendation
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  user:
    environment:
      - TLS
    image: igorrudyk1/hotel_reserv_user_single_node:latest
    entrypoint: user
    depends_on:
      - mongodb-user
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  reservation:
    environment:
      - TLS
    image: igorrudyk1/hotel_reserv_reserve_single_node:latest
    entrypoint: reservation
    depends_on:
      - mongodb-reservation
      - memcached-reserve
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-rate:
    image: memcached
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-profile:
    image: memcached
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-reserve:
    image: memcached
    hostname: user-memcached
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-geo:
    image: mongo:4.4.6
    hostname: geo-db
    volumes:
      - geo:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-profile:
    image: mongo:4.4.6
    hostname: profile-db
    volumes:
      - profile:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-rate:
    image: mongo:4.4.6
    hostname: rate-db
    volumes:
      - rate:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-recommendation:
    image: mongo:4.4.6
    hostname: recommendation-db
    volumes:
      - recommendation:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-reservation:
    image: mongo:4.4.6
    hostname: reservation-db
    volumes:
      - reservation:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-user:
    image: mongo:4.4.6
    hostname: user-db
    volumes:
      - user:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user:
  
