apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-recommendation
  name: mongodb-recommendation
spec:
  ports:
    - name: "mongodb-recommendation"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-recommendation
status:
  loadBalancer: {}
